/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhd_ndktest_JNIS */

#ifndef _Included_com_lhd_ndktest_JNIS
#define _Included_com_lhd_ndktest_JNIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhd_ndktest_JNIS
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lhd_ndktest_JNIS_helloJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_lhd_ndktest_JNIS
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lhd_ndktest_JNIS_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lhd_ndktest_JNIS
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lhd_ndktest_JNIS_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lhd_ndktest_JNIS
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lhd_ndktest_JNIS_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

JNIEXPORT jintArray JNICALL Java_com_lhd_ndktest_JNIS_checkPwd
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
