/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lhd_ndktest_JNIS */

#ifndef _Included_com_lhd_ndktest_JNIS
#define _Included_com_lhd_ndktest_JNIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lhd_ndktest_JNIS
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
jstring Java_com_lhd_ndktest_JNIS_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
